name: Construir e Publicar APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para criar o Release automaticamente
    steps:
      - name: Pegar meus arquivos
        uses: actions/checkout@v4

      - name: Instalar Java (Requisito do Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter (Motor do Flet)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências (Flet)
        run: pip install -r requirements.txt

      - name: Fabricar o Aplicativo (APK)
        run: flet build apk

      - name: Publicar APK no Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Versão 1.0.${{ github.run_number }}"
          body: "Nova versão automática do aplicativo de Controlo Financeiro gerada via GitHub Actions."
          files: build/apk/**/*.apk
          draft: false
          prerelease: false
